apiVersion: apps/v1
kind: Deployment
metadata:
  name: hono-engine
  namespace: hono-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hono-engine
  template:
    metadata:
      labels:
        app: hono-engine
    spec:
      containers:
        - name: hono-engine
          image: hono-engine:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
